CREATE TABLE classes (ID INTEGER, name TEXT);
INSERT INTO classes (ID, name) VALUES (0, 'Área não observada');
INSERT INTO classes (ID, name) VALUES (1, 'Floresta');
INSERT INTO classes (ID, name) VALUES (2, 'Não floresta');
INSERT INTO classes (ID, name) VALUES (3, 'Água');
INSERT INTO classes (ID, name) VALUES (4, 'Vegetação não florestal');
INSERT INTO classes (ID, name) VALUES (5, 'Pastagem');
INSERT INTO classes (ID, name) VALUES (6, 'Agricultura');
INSERT INTO classes (ID, name) VALUES (7, 'Floresta plantada');
INSERT INTO classes (ID, name) VALUES (8, 'Floresta da zona costeira');
